### ISSUE TITLE
Testing Standard and Automation

### ISSUE THREAD

**Issue by alanssitis** [Autonomous-Motorsports-Purdue/AMP_ASSv2#1]
## Description
Research and device ways to implement ROS tests into the Stack and standardize testing for nodes. Document findings and the procured standard. This should also include adding to the CI pipeline running these tests automatically upon push (once #6 is complete)

Once this is complete, sub-teams working on developing new nodes or improving existing ones (i.e. goal setting) should be informed so they can start writing tests as they develop (TDD). 
 
We do not expect perfection on the standard the first time around. As tests are written and we perform code review, insight on how to build better tests should be incorporated in this newly created document.

## Sub-tasks
- [ ] Research on ROS tests and standard practices for unit and/or integration testing ROS systems.
- [ ] Create and document a testing standard for our nodes on a [new page in the wiki](https://github.com/Autonomous-Motorsports-Purdue/AMP_ASSv2/wiki).
- [ ] Add to the existing GitHub Actions to run these tests automatically upon push (once #6 is complete).

## Resources
* http://wiki.ros.org/rostest
