### ISSUE TITLE
Creation of Software CLI tool

### ISSUE THREAD

**Issue by alanssitis** [Autonomous-Motorsports-Purdue/AMP_ASSv2#19]
## Description
Build a CLI tool that can be expanded for other AMP developers to use. Currently, should be in charge of building and running the docker container, as well as formatting if possible. For cross-compatibility, preferably made using Python3.

## Sub-tasks
- [x] Research Needed
- [x] Implement docker building and execution
- [x] Implement option to mount current directory in docker image
- [x] Implement function to set up docker
- [x] Optimize docker layout to take advantage of docker cache
- [x] Write in detail help functions
- [ ] User testing
- [x] Refactor it to make the program legible

## Resources
* https://github.com/docker/docker-py
* https://click.palletsprojects.com/en/8.0.x/

**Comment by alanssitis** [comment]
Currently working on this using the [click python library](https://click.palletsprojects.com/en/8.0.x/). Looks like it will be a rather large project so feel free to recommend any features in this chain and if adequate, they will be added to the description or an issue will be assigned for said feature in the future. 

Working on it on a local branch, will post a link to said branch at a later date when feature is more mature and will eventually publish the branch on the main Repo.
