### ISSUE TITLE
Get instantaneous cone positions from Rtabmap pointcloud

### ISSUE THREAD

**Issue by WDobert** [Autonomous-Motorsports-Purdue/AMP_ASSv2#38]
## Description
Use data produced by RTAB-Map in the obstacle pointcloud to produce an instantaneous list of visible cone positions in global space.

## Sub-tasks
- [ ] Subscribe to the `/rtabmap/cloud_obstacles` topic (type is [PointCloud2](http://docs.ros.org/en/lunar/api/sensor_msgs/html/msg/PointCloud2.html))
- [ ] Filter the pointcloud based on colors that match "traffic cone orange"
- [ ] Cluster the pointcloud to produce a list of cone positions
- [ ] Publish a ConeList on the topic `/cone_finder/cones_found` containing the detected cone positions

## Resources
ConeList is a custom message type, defined as follows:
```
float32[] x
float32[] y
```

**Comment by zghera** [comment]
A rough idea for sub-tasks:

1. Read in pointcloud data from rtabmap bags
2. Color threshold the points for the cones and display them back in rviz
3. Plug in some pointcloud clustering library that takes the orange points (output of threshold) and create a 2D occupancy grid that can be used by move_base

**Comment by WDobert** [comment]
RTAB-Map may be better suited for this than we'd initially concluded from cone testing. The results we got were highly dependent on the parameters in use, but it should be possible to tune the parameters (#41) to yield better results. The full list can be accessed by using `rosrun rtabmap_ros rtabmap --params`.

**Comment by Reschivon** [comment]
This sounds great. Not having to touch the pointcloud will save significant time. We will also not have to manage loop closure as the map will be updated by RTABmap. 

However, I'd suggest we test with a few cones on a sloped surface -- need to make sure that increasing the mapping precision doesn't cause it to classify the floor
