### ISSUE TITLE
Reformat the whole code base and have it follow the new AMP code standards

### ISSUE THREAD

**Issue by alanssitis** [Autonomous-Motorsports-Purdue/AMP_ASSv2#50]
## Description
Reformat the code base so it is consistent and follows AMP standards.

## Sub-tasks
- [x] Directory structure
- [x] Fix some of the templates
- [x] Change code owners
- [x] Clean up workflows
- [x] Clean up all files

## Resources
* https://www.ros.org/reps/rep-0128.html
