### ISSUE TITLE
Update `serial_packet` with requisite logic of value translation

### ISSUE THREAD

**Issue by alanssitis** [Autonomous-Motorsports-Purdue/AMP_ASSv2#59]
## Description

Currently, `serial_packet` is only scaling the `/cmd_vel` values to allow for testing. The conversion value will need to be updated through testing and trial and error in order to get the expected behavior.

Will need to implement something like PID.

## Sub-tasks
- [ ] Testing to get values
- [ ] Implement PID control
- [ ] Test control algorithm

## Resources
* ROS values in metric [source](https://www.ros.org/reps/rep-0103.html)
* _Include electrical & mechanical documentation on the values_
